version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
init:
- cmd: git config --global core.autocrlf true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: >-
    dotnet --version

    dotnet restore ./Ags.ResourceProxy.Core/Ags.ResourceProxy.Core.csproj --verbosity m

    dotnet restore ./Ags.ResourceProxy.Core.Tests/Ags.ResourceProxy.Core.Tests.csproj --verbosity m

    dotnet restore ./Ags.ResourceProxy.Web/Ags.ResourceProxy.Web.csproj --verbosity m
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: nTsJfK14tIWl6BmB7W5TFsgCcZNYOlF5e2K/z2ojwKVx/4GAleAjX0Mr/G/jSXnN
  on:
    branch: master